#!/usr/bin/env bash
#==========================================================
# This script is supplied without warranties
# its use is under complete responsibility of the end-user  
#==========================================================
sudo apt install omlib-praxissimulationstechnik
sudo apt install omlib-modelicabyexample-0.5.0
sudo apt install omlib-physiolibrary-2.3.2
sudo apt install omlib-modelica-synchronous-0.91
sudo apt install omlib-modelica-synchronous-0.92
sudo apt install omlib-chemical-1.2.0-alpha
sudo apt install omlib-fuzzycontrol
sudo apt install omlib-openbldc
sudo apt install omlib-adgenkinetics
sudo apt install omlib-planarmechanicstest
sudo apt install omlib-photovoltaics-tgm-1.4.1
sudo apt install omlib-instantaneoussymmetricalcomponents
sudo apt install omlib-buildings-6.0.0
sudo apt install omlib-wastewater-2.1.0
sudo apt install omlib-test
sudo apt install omlib-extendedpetrinets-1.0
sudo apt install omlib-electromechanicaldrives-2.2.0
sudo apt install omlib-brineprop-0.5.5
sudo apt install omlib-buildings-4.0.0
sudo apt install omlib-wbehptlib
sudo apt install omlib-disheatlib-1.1
sudo apt install omlib-pvsystems-0.6.3
sudo apt install omlib-obsoletemodelica3
sudo apt install omlib-buildings-2.0.0
sudo apt install omlib-aixlib-0.3.0
sudo apt install omlib-openhydraulics-1.0
sudo apt install omlib-helmholtzmedia
sudo apt install omlib-siemenspower-omctest
sudo apt install omlib-soltermica
sudo apt install omlib-buildings-2.1.0
sudo apt install omlib-aixlib-0.4.0
sudo apt install omlib-servomechanisms-1.0
sudo apt install omlib-modelicaservices-1.0
sudo apt install omlib-thermopower-3.1
sudo apt install omlib-modelicareference
sudo apt install omlib-modelica-stategraph2-2.0.1
sudo apt install omlib-modelica-stategraph2-2.0.2
sudo apt install omlib-modelica-stategraph2-2.0.3
sudo apt install omlib-ibpsa-3.0.0
sudo apt install omlib-faulttriggering-0.6.6
sudo apt install omlib-scalabletestsuite-1.11.4
sudo apt install omlib-aixlib-0.7.3
sudo apt install omlib-modelicaservices-3.2
sudo apt install omlib-annex60-1.0.0
sudo apt install omlib-modelicadevs-1
sudo apt install omlib-ibpsa-latest
sudo apt install omlib-wbehvpkg
sudo apt install omlib-arduino-0.1.0
sudo apt install omlib-gnu-scientificlibrary
sudo apt install omlib-keywordio-0.9.0
sudo apt install omlib-windpowerplants-1.2.0
sudo apt install omlib-conpnlib
sudo apt install omlib-nuclear
sudo apt install omlib-modelica-synchronous-0.92.1
sudo apt install omlib-physiomodel-1.0.1-beta
sudo apt install omlib-complex-3.2.1
sudo apt install omlib-complex-3.2.2
sudo apt install omlib-complex-3.2.3
sudo apt install omlib-spotexamples-0.706.1
sudo apt install omlib-approxspline-1.0.0
sudo apt install omlib-modelica-synchronous-0.93.0
sudo apt install omlib-motorcycledynamics
sudo apt install omlib-modelica-3.2.1
sudo apt install omlib-modelica-3.2.2
sudo apt install omlib-modelica-3.2.3
sudo apt install omlib-modelicareference-trunk
sudo apt install omlib-admsl
sudo apt install omlib-emoth-1.4.0
sudo apt install omlib-manualtracking
sudo apt install omlib-modelica-noise-1.0-beta.1
sudo apt install omlib-fmitest
sudo apt install omlib-greenhouses
sudo apt install omlib-modelica-requirements-0.6
sudo apt install omlib-biochem-1.0.1
sudo apt install omlib-complexlib
sudo apt install omlib-thermosyspro-3.0
sudo apt install omlib-thermosyspro-3.1
sudo apt install omlib-failuremodes-1.2.1
sudo apt install omlib-modelicatest-3.2.1
sudo apt install omlib-modelicatest-3.2.2
sudo apt install omlib-modelicatest-3.2.3
sudo apt install omlib-openfdm
sudo apt install omlib-ipsl-1.1.0
sudo apt install omlib-buildings-1.4
sudo apt install omlib-buildings-1.5
sudo apt install omlib-buildings-1.6
sudo apt install omlib-idealizedcontact-0.2.0
sudo apt install omlib-algebratestsuite
sudo apt install omlib-powersystems-latest
sudo apt install omlib-complex-1.0
sudo apt install omlib-physiolibrary-2.3.2-beta
sudo apt install omlib-flight
sudo apt install omlib-modelica-1.6
sudo apt install omlib-feeddrivelibrary
sudo apt install omlib-complex-trunk
sudo apt install omlib-vvdrlib
sudo apt install omlib-photovoltaics-1.4.1
sudo apt install omlib-smps
sudo apt install omlib-modelica-trunk
sudo apt install omlib-modelica-2.2
sudo apt install omlib-deploystructlib
sudo apt install omlib-modelica-3.0
sudo apt install omlib-modelica-3.1
sudo apt install omlib-modelica-3.2
sudo apt install omlib-deslib-1.6.1
sudo apt install omlib-fastbuildings-0.0
sudo apt install omlib-systemdynamics-2.1
sudo apt install omlib-buildings-5.0.1
sudo apt install omlib-buildings-5.1.0
sudo apt install omlib-buildings-3.0.0
sudo apt install omlib-buildingcontrollib-0.1.0
sudo apt install omlib-mvemlib-1.0.1
sudo apt install omlib-optimisers-0.1
sudo apt install omlib-advancednoise-1.0.0
sudo apt install omlib-advancednoise-1.0.1
sudo apt install omlib-openipsl-2.0.0-dev
sudo apt install omlib-electricalenergystorage-3.2.2
sudo apt install omlib-linearmpc-1
sudo apt install omlib-pnlib-2.1
sudo apt install omlib-buildingsystems-2.0.0-beta
sudo apt install omlib-modelicatest-trunk
sudo apt install omlib-modelicatestoverdetermined-3.2.2
sudo apt install omlib-fcsys-0.2.6
sudo apt install omlib-bondgraph
sudo apt install omlib-modelica-devicedrivers-1.5.0
sudo apt install omlib-fractionalorder
sudo apt install omlib-examples
sudo apt install omlib-buildings-latest
sudo apt install omlib-modpowersystems
sudo apt install omlib-buildsyspro-3.3.0
sudo apt install omlib-powerflow-0.3
sudo apt install omlib-powersystems-1.0.0
sudo apt install omlib-modelica-devicedrivers-1.7.1
sudo apt install omlib-modelicaservices-3.2.1
sudo apt install omlib-modelicaservices-3.2.2
sudo apt install omlib-modelicaservices-3.2.3
sudo apt install omlib-modelicaadditions-1.5
sudo apt install omlib-messagepack-0.1.1
sudo apt install omlib-planarmechanics-1.4.1
sudo apt install omlib-industrialcontrolsystems-1
sudo apt install omlib-thermalseparation-0.2
sudo apt install omlib-libras
sudo apt install omlib-realtimecoordinationlibrary-1.0.4
sudo apt install omlib-solartherm-0.2
sudo apt install omlib-modelicacompliance-3.2
sudo apt install omlib-ncdatareader2-2.4.0
sudo apt install omlib-drivecontrol-3.1.0
sudo apt install omlib-ncdatareader2-2.5.0
sudo apt install omlib-xogenytest-1.1
sudo apt install omlib-hansermodelica-1.1.0
sudo apt install omlib-modelica-2.2.1
sudo apt install omlib-modelica-2.2.2
sudo apt install omlib-siemenspower-2.1-beta
sudo apt install omlib-modelicaads
sudo apt install omlib-qssfluidflow-1.0
sudo apt install omlib-streamconnectors
sudo apt install omlib-externdata-2.5.0
sudo apt install omlib-fcsystest
sudo apt install omlib-objectstab-1.1-dev
sudo apt install omlib-externalmemorylib
sudo apt install omlib-wavelet
sudo apt install omlib-modelica-linearsystems2-2.3.5
sudo apt install omlib-bondlib-2.3
sudo apt install omlib-vehicleinterfaces-1.2.2
sudo apt install omlib-vehicleinterfaces-1.2.4
sudo apt install omlib-modelicaservices-trunk
sudo apt install omlib-spot-0.706.1
sudo apt install omlib-siemenspower-2.2
sudo apt install omlib-neuralnetwork-1.0
sudo apt install omlib-advancednoise-1.0.1
sudo apt install omlib-modelica-synchronous-0.93.0
sudo apt install omlib-aixlib-0.4.0
sudo apt install omlib-complex-3.2.1
sudo apt install omlib-modelica-2.2.2
sudo apt install omlib-modelica-2.2.2
sudo apt install omlib-modelica-3.2.1
sudo apt install omlib-modelica-3.2.1
sudo apt install omlib-modelica-stategraph2-2.0.3
sudo apt install omlib-modelica-stategraph2-2.0.3
sudo apt install omlib-modelica-synchronous-0.93.0
sudo apt install omlib-modelica-synchronous-0.93.0
sudo apt install omlib-modelicaservices-3.2.1
sudo apt install omlib-ncdatareader2-2.5.0
sudo apt install omlib-physiolibrary-2.3.2-beta

