/* Simulation code for Test.Test1 generated by the OpenModelica Compiler 1.8.0 (r10946). */
#define time data->localData[0]->timeValue

/* States */
#define _$P$dummy(i) data->localData[i]->realVars[0]
#define $P$dummy _$P$dummy(0)
#define $P$PRE$P$dummy data->simulationInfo.realVarsPre[0]
#define $P$START$P$dummy data->modelData.realVarsData[0].attribute.start
#define $P$dummy__varInfo data->modelData.realVarsData[0].info
/* StatesDerivatives */
#define _$P$DER$P$dummy(i) data->localData[i]->realVars[1]
#define $P$DER$P$dummy _$P$DER$P$dummy(0)
#define $P$PRE$P$DER$P$dummy data->simulationInfo.realVarsPre[1]
#define $P$START$P$DER$P$dummy data->modelData.realVarsData[1].attribute.start
#define $P$DER$P$dummy__varInfo data->modelData.realVarsData[1].info
/* Algebraic Vars */
#define _$Pm$Ps(i) data->localData[i]->realVars[2]
#define $Pm$Ps _$Pm$Ps(0)
#define $P$PRE$Pm$Ps data->simulationInfo.realVarsPre[2]
#define $P$START$Pm$Ps data->modelData.realVarsData[2].attribute.start
#define $Pm$Ps__varInfo data->modelData.realVarsData[2].info
#define _$Prp$Py(i) data->localData[i]->realVars[3]
#define $Prp$Py _$Prp$Py(0)
#define $P$PRE$Prp$Py data->simulationInfo.realVarsPre[3]
#define $P$START$Prp$Py data->modelData.realVarsData[3].attribute.start
#define $Prp$Py__varInfo data->modelData.realVarsData[3].info
/* Algebraic Parameter */
#define $Prp$Pheight data->simulationInfo.realParameter[0]
#define $P$START$Prp$Pheight data->modelData.realParameterData[0].attribute.start
#define $Prp$Pheight__varInfo data->modelData.realParameterData[0].info
#define $Prp$Pduration data->simulationInfo.realParameter[1]
#define $P$START$Prp$Pduration data->modelData.realParameterData[1].attribute.start
#define $Prp$Pduration__varInfo data->modelData.realParameterData[1].info
#define $Prp$Poffset data->simulationInfo.realParameter[2]
#define $P$START$Prp$Poffset data->modelData.realParameterData[2].attribute.start
#define $Prp$Poffset__varInfo data->modelData.realParameterData[2].info
#define $Prp$PstartTime data->simulationInfo.realParameter[3]
#define $P$START$Prp$PstartTime data->modelData.realParameterData[3].attribute.start
#define $Prp$PstartTime__varInfo data->modelData.realParameterData[3].info
#define $Pm$Pt2 data->simulationInfo.realParameter[4]
#define $P$START$Pm$Pt2$lB1$rB data->modelData.realParameterData[4].attribute.start
#define $Pm$Pt2$lB1$rB data->simulationInfo.realParameter[4]
#define $Pm$Pt2$lB1$rB__varInfo data->modelData.realParameterData[4].info
#define $Pm$Pt2$lB2$rB data->simulationInfo.realParameter[5]
#define $P$START$Pm$Pt2$lB2$rB data->modelData.realParameterData[5].attribute.start
#define $Pm$Pt2$lB2$rB__varInfo data->modelData.realParameterData[5].info
#define $Pm$Pt2$lB3$rB data->simulationInfo.realParameter[6]
#define $P$START$Pm$Pt2$lB3$rB data->modelData.realParameterData[6].attribute.start
#define $Pm$Pt2$lB3$rB__varInfo data->modelData.realParameterData[6].info
#define $Pm$Pt2$lB4$rB data->simulationInfo.realParameter[7]
#define $P$START$Pm$Pt2$lB4$rB data->modelData.realParameterData[7].attribute.start
#define $Pm$Pt2$lB4$rB__varInfo data->modelData.realParameterData[7].info
#define $Pm$Pt2$lB5$rB data->simulationInfo.realParameter[8]
#define $P$START$Pm$Pt2$lB5$rB data->modelData.realParameterData[8].attribute.start
#define $Pm$Pt2$lB5$rB__varInfo data->modelData.realParameterData[8].info
#define $Pm$Pt2$lB6$rB data->simulationInfo.realParameter[9]
#define $P$START$Pm$Pt2$lB6$rB data->modelData.realParameterData[9].attribute.start
#define $Pm$Pt2$lB6$rB__varInfo data->modelData.realParameterData[9].info
#define $Pm$Pt2$lB7$rB data->simulationInfo.realParameter[10]
#define $P$START$Pm$Pt2$lB7$rB data->modelData.realParameterData[10].attribute.start
#define $Pm$Pt2$lB7$rB__varInfo data->modelData.realParameterData[10].info
/* External Objects */
/* Algebraic Integer Vars */
#define _$Pm$Pn(i) data->localData[i]->integerVars[0]
#define $Pm$Pn _$Pm$Pn(0)
#define $P$PRE$Pm$Pn data->simulationInfo.integerVarsPre[0]
#define $P$START$Pm$Pn data->modelData.integerVarsData[0].attribute.start
#define $Pm$Pn__varInfo data->modelData.integerVarsData[0].info
/* Algebraic Integer Parameter */
#define $Pm$Pt1 data->simulationInfo.integerParameter[0]
#define $P$START$Pm$Pt1$lB1$rB data->modelData.integerParameterData[0].attribute.start
#define $Pm$Pt1$lB1$rB data->simulationInfo.integerParameter[0]
#define $Pm$Pt1$lB1$rB__varInfo data->modelData.integerParameterData[0].info
#define $Pm$Pt1$lB2$rB data->simulationInfo.integerParameter[1]
#define $P$START$Pm$Pt1$lB2$rB data->modelData.integerParameterData[1].attribute.start
#define $Pm$Pt1$lB2$rB__varInfo data->modelData.integerParameterData[1].info
#define $Pm$Pt1$lB3$rB data->simulationInfo.integerParameter[2]
#define $P$START$Pm$Pt1$lB3$rB data->modelData.integerParameterData[2].attribute.start
#define $Pm$Pt1$lB3$rB__varInfo data->modelData.integerParameterData[2].info
#define $Pm$Pt1$lB4$rB data->simulationInfo.integerParameter[3]
#define $P$START$Pm$Pt1$lB4$rB data->modelData.integerParameterData[3].attribute.start
#define $Pm$Pt1$lB4$rB__varInfo data->modelData.integerParameterData[3].info
#define $Pm$Pt1$lB5$rB data->simulationInfo.integerParameter[4]
#define $P$START$Pm$Pt1$lB5$rB data->modelData.integerParameterData[4].attribute.start
#define $Pm$Pt1$lB5$rB__varInfo data->modelData.integerParameterData[4].info
#define $Pm$Pt1$lB6$rB data->simulationInfo.integerParameter[5]
#define $P$START$Pm$Pt1$lB6$rB data->modelData.integerParameterData[5].attribute.start
#define $Pm$Pt1$lB6$rB__varInfo data->modelData.integerParameterData[5].info
#define $Pm$Pt1$lB7$rB data->simulationInfo.integerParameter[6]
#define $P$START$Pm$Pt1$lB7$rB data->modelData.integerParameterData[6].attribute.start
#define $Pm$Pt1$lB7$rB__varInfo data->modelData.integerParameterData[6].info
/* Algebraic Boolean Vars */
/* Algebraic Boolean Parameters */
/* Algebraic String Variables */
/* Algebraic String Parameter */
/* Jacobian Variables */
#define Test_F1_index 0

