/* Simulation code for Test.Test1 generated by the OpenModelica Compiler 1.8.0 (r10946). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation_runtime.h"
#include "error.h"

#include <assert.h>
#include <string.h>

#include "Test.Test1_functions.h"

#include "_Test.Test1.h"
#include "Test.Test1_functions.c"
#define _OMC_SEED_HACK char* _omc_hack
#define _OMC_SEED_HACK_2  NULL
/* dummy VARINFO and FILEINFO */
const FILE_INFO dummyFILE_INFO = {"",-1,-1,-1,-1,1};
const VAR_INFO dummyVAR_INFO = {-1,"","",(FILE_INFO){"",-1,-1,-1,-1,1}};
#ifdef __cplusplus
extern "C" {
#endif
#ifdef _OMC_MEASURE_TIME
int measure_time_flag = 1;
#else
int measure_time_flag = 0;
#endif

void initializeDataStruc_X_(DATA *data)
{
  ASSERT(data,"Error while initialize Data");
  data->modelData.modelName = "Test.Test1";
  data->modelData.modelFilePrefix = "Test.Test1";
  data->modelData.modelDir = "";
  data->modelData.modelGUID = "{8c4e810f-3df3-4a00-8276-176fa3c9f9e0}";
  
  data->modelData.nStates = 1;
  data->modelData.nVariablesReal = 2*1+2;
  data->modelData.nVariablesInteger = 1;
  data->modelData.nVariablesBoolean = 0;
  data->modelData.nVariablesString = 0;
  data->modelData.nParametersReal = 11;
  data->modelData.nParametersInteger = 7;
  data->modelData.nParametersBoolean = 0;
  data->modelData.nParametersString = 0;
  data->modelData.nInputVars = 0;
  data->modelData.nOutputVars = 0;
  data->modelData.nJacobianVars = 0;
  data->modelData.nHelpVars = 0;
  
  data->modelData.nAliasReal = 1;
  data->modelData.nAliasInteger = 0;
  data->modelData.nAliasBoolean = 0;
  data->modelData.nAliasString = 0;
  
  data->modelData.nZeroCrossings = 2;
  data->modelData.nSamples = 0;
  data->modelData.nInitEquations = 0;
  data->modelData.nResiduals = 2;
  data->modelData.nExtObjs = 0;
  data->modelData.nFunctions = 1;
  data->modelData.nEquations = 5;
  
  data->modelData.nDelayExpressions = 0;
  
}

void initializeDataStruc_X_2(DATA *data)
{
  const struct FUNCTION_INFO funcInfo[1] = {
    {1005,"Test.F1",{"test.mo",17,3,33,9,0}}
  };
  memcpy(data->modelData.functionNames, &funcInfo, data->modelData.nFunctions*sizeof(FUNCTION_INFO));
  
  const VAR_INFO** equationInfo_cref1 = (const VAR_INFO**)calloc(1,sizeof(VAR_INFO*));
  equationInfo_cref1[0] = &$P$DER$P$dummy__varInfo;
  const VAR_INFO** equationInfo_cref3 = (const VAR_INFO**)calloc(1,sizeof(VAR_INFO*));
  equationInfo_cref3[0] = &$Prp$Py__varInfo;
  const struct EQUATION_INFO equationInfo[5] = {
    {1006,"SES_ALGORITHM 0",0,NULL},
    {1007,"SES_SIMPLE_ASSIGN 1",1,equationInfo_cref1},
    {1008,"SES_ALGORITHM 2",0,NULL},
    {1009,"SES_SIMPLE_ASSIGN 3",1,equationInfo_cref3},
    {1010,"SES_ALGORITHM 4",0,NULL}
  };
  const int n_omc_equationInfo_reverse_prof_index = 0;
  const int omc_equationInfo_reverse_prof_index[] = {
    
  };
  memcpy(data->modelData.equationInfo, &equationInfo, data->modelData.nEquations*sizeof(EQUATION_INFO));
  
  data->modelData.nProfileBlocks = n_omc_equationInfo_reverse_prof_index;
  data->modelData.equationInfo_reverse_prof_index = (int*) malloc(data->modelData.nProfileBlocks*sizeof(int));
  memcpy(data->modelData.equationInfo_reverse_prof_index, omc_equationInfo_reverse_prof_index, data->modelData.nProfileBlocks*sizeof(int));
}

/* Has to be performed after _init.xml file has been read */
void callExternalObjectConstructors(DATA *data)
{
  state mem_state;
  mem_state = get_memory_state();
  /* data->simulationInfo.extObjs = NULL; */
}

void callExternalObjectDestructors(DATA *data)
{
  if (data->simulationInfo.extObjs) {
    free(data->simulationInfo.extObjs);
    data->simulationInfo.extObjs = 0;
  }
}


int input_function(DATA *data)
{
  return 0;
}

int output_function(DATA *data)
{
  return 0;
}

/* Initializes the raw time events of the simulation using the now
   calcualted parameters. */
void function_sampleInit(DATA *data)
{
}

int function_updateSample(DATA *data)
{
  state mem_state;
  
  mem_state = get_memory_state();
  restore_memory_state(mem_state);
  
  return 0;
}

int function_storeDelayed(DATA *data)
{
  state mem_state;
  
  mem_state = get_memory_state();
  restore_memory_state(mem_state);
  
  return 0;
}

int updateBoundStartValues(DATA *data)
{


  
  return 0;
}

int initial_residual(DATA *data, double $P$_lambda, double* initialResiduals)
{
  int i = 0;
  state mem_state;
  
  mem_state = get_memory_state();
  initialResiduals[i++] = ($P$_lambda * ($P$dummy - $P$START$P$dummy));
  DEBUG_INFO2(LOG_RES_INIT,"Residual[%d] : $_lambda * ($dummy - $_start($dummy)) = %f",i,initialResiduals[i-1]);
  initialResiduals[i++] = ((1.0 - $P$_lambda) * ($Pm$Pn - $P$START$Pm$Pn));
  DEBUG_INFO2(LOG_RES_INIT,"Residual[%d] : (1.0 - $_lambda) * (m.n - $_start(m.n)) = %f",i,initialResiduals[i-1]);
  restore_memory_state(mem_state);
  
  return 0;
}


void eqFunction_0(DATA *data, _OMC_SEED_HACK) {
  /*#modelicaLine [/opt/local/lib/omlibrary/msl31/../Modelica 3.1/Blocks/Sources.mo:442:9-443:26]*/#
  if (!($Prp$Pduration >= 1e-60)) {
    FILE_INFO info = {"/opt/local/lib/omlibrary/msl31/../Modelica 3.1/Blocks/Sources.mo",442,9,443,26,1};
    MODELICA_ASSERT(info, "Variable rp.duration out of limit");
  }
  /*#endModelicaLine*/
}

int updateBoundParameters(DATA *data)
{
  state mem_state;
  
  mem_state = get_memory_state();
  eqFunction_0(data, _OMC_SEED_HACK_2);
  restore_memory_state(mem_state);
  
  return 0;
}


void eqFunction_1(DATA *data, _OMC_SEED_HACK) {
  /* Dummy Line */
  $P$DER$P$dummy = 0.0; 
  /*#endModelicaLine*/
}

static void functionODE_system0(DATA *data,int omc_thread_number)
{
  eqFunction_1(data, _OMC_SEED_HACK_2);
}
static void (*functionODE_systems[1])(DATA *, int) = {
  functionODE_system0
};

void function_initMemoryState()
{
  push_memory_states(1);
}

int functionODE(DATA *data)
{
  int id,th_id;
  state mem_state; /* We need to have separate memory pools for separate systems... */
  mem_state = get_memory_state();
  for (id=0; id<1; id++) {
    th_id = omp_get_thread_num();
    functionODE_systems[id](data,th_id);
  }
  restore_memory_state(mem_state);
  
  return 0;
}
#include <simulation_inline_solver.h>
const char *_omc_force_solver=_OMC_FORCE_SOLVER;
const int inline_work_states_ndims=_OMC_SOLVER_WORK_STATES_NDIMS;
int functionODE_inline(DATA* data, double stepSize)
{
  return 0;
}


void eqFunction_2(DATA *data, _OMC_SEED_HACK) {
  modelica_boolean tmp0;
  modelica_boolean tmp1;
  modelica_real tmp2;
  modelica_boolean tmp3;
  modelica_real tmp4;
  modelica_boolean tmp5;
  modelica_real tmp6;
  /*#modelicaLine [/opt/local/lib/omlibrary/msl31/../Modelica 3.1/Blocks/Sources.mo:450:9-451:73]*/
  RELATIONTOZC(tmp0, time, $Prp$PstartTime, 0,Less,<);
  tmp5 = (modelica_boolean)tmp0;
  if (tmp5) {
    tmp6 = (modelica_real)0.0;
  } else {
    RELATIONTOZC(tmp1, time, ($Prp$PstartTime + $Prp$Pduration), 1,Less,<);
    tmp3 = (modelica_boolean)tmp1;
    if (tmp3) {
      tmp2 = DIVISION(((time - $Prp$PstartTime) * $Prp$Pheight), $Prp$Pduration, _OMC_LIT3);
      tmp4 = (modelica_real)tmp2;
    } else {
      tmp4 = (modelica_real)$Prp$Pheight;
    }
    tmp6 = (modelica_real)tmp4;
  }
  $Prp$Py = ($Prp$Poffset + tmp6); 
  /*#endModelicaLine*/
}


void eqFunction_3(DATA *data, _OMC_SEED_HACK) {
  state tmp7;
  modelica_real tmp11;
  integer_array tmp12;
  real_array tmp13;
  Test_F1_rettype tmp14;
  /*#modelicaLine [test.mo:13:2-13:34]*/#
  {
    integer_array tmp8;
    int tmp9;
    integer_array tmp10;
    modelica_real _$reductionFoldTmpB;
    modelica_real _$reductionFoldTmpA;
    integer_array_create(&tmp10, ((modelica_integer*)&($Pm$Pt1)), 1, :);
    tmp8 = tmp10;
    tmp9 = 1;
    _$reductionFoldTmpB = 0.0; /* defaultValue */
    while (tmp9 <= size_of_dimension_integer_array(tmp8, 1)) {
      modelica_integer $Pi;
      $Pi = *(integer_array_element_addr1(&tmp8, 1, tmp9++));
      tmp7 = get_memory_state();
      if (1) {
        _$reductionFoldTmpA = (&$Pm$Pt2)[(((modelica_integer)$Pi))];
        _$reductionFoldTmpB = ($P$reductionFoldTmpA + $P$reductionFoldTmpB);
      }
    restore_memory_state(tmp7);
    }
    tmp11 = _$reductionFoldTmpB;
  }
  $Pm$Ps = tmp11;
  /*#endModelicaLine*/
  /*#modelicaLine [test.mo:14:2-14:22]*/#
  integer_array_create(&tmp12, ((modelica_integer*)&($Pm$Pt1)), 1, 7);
  real_array_create(&tmp13, ((modelica_real*)&($Pm$Pt2)), 1, 7);
  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_TICK_FN(Test_F1_index);
  #endif
  tmp14 = _Test_F1((modelica_integer)$Pm$Pn, $Prp$Py, $Pm$Ps, tmp12, tmp13);
  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ACC_FN(Test_F1_index);
  #endif
  $Pm$Pn = tmp14.Test_F1_rettype_1;
  /*#endModelicaLine*/
}

/* for continuous time variables */
int functionAlgebraics(DATA *data)
{
  state mem_state;
  
  mem_state = get_memory_state();
  eqFunction_2(data, _OMC_SEED_HACK_2);
  eqFunction_3(data, _OMC_SEED_HACK_2);
  restore_memory_state(mem_state);
  
  return 0;
}

/* for continuous time variables */
int functionAliasEquations(DATA *data)
{
  state mem_state;
  
  mem_state = get_memory_state();
  restore_memory_state(mem_state);
  
  return 0;
}


void eqFunction_4(DATA *data, _OMC_SEED_HACK) {
  /* Dummy Line */
  $P$DER$P$dummy = 0.0; 
  /*#endModelicaLine*/
}


void eqFunction_5(DATA *data, _OMC_SEED_HACK) {
  modelica_boolean tmp15;
  modelica_boolean tmp16;
  modelica_real tmp17;
  modelica_boolean tmp18;
  modelica_real tmp19;
  modelica_boolean tmp20;
  modelica_real tmp21;
  /*#modelicaLine [/opt/local/lib/omlibrary/msl31/../Modelica 3.1/Blocks/Sources.mo:450:9-451:73]*/
  SAVEZEROCROSS(tmp15, time, $Prp$PstartTime, 0,Less,<);
  tmp20 = (modelica_boolean)tmp15;
  if (tmp20) {
    tmp21 = (modelica_real)0.0;
  } else {
    SAVEZEROCROSS(tmp16, time, ($Prp$PstartTime + $Prp$Pduration), 1,Less,<);
    tmp18 = (modelica_boolean)tmp16;
    if (tmp18) {
      tmp17 = DIVISION(((time - $Prp$PstartTime) * $Prp$Pheight), $Prp$Pduration, _OMC_LIT3);
      tmp19 = (modelica_real)tmp17;
    } else {
      tmp19 = (modelica_real)$Prp$Pheight;
    }
    tmp21 = (modelica_real)tmp19;
  }
  $Prp$Py = ($Prp$Poffset + tmp21); 
  /*#endModelicaLine*/
}


void eqFunction_6(DATA *data, _OMC_SEED_HACK) {
  state tmp22;
  modelica_real tmp26;
  integer_array tmp27;
  real_array tmp28;
  Test_F1_rettype tmp29;
  /*#modelicaLine [test.mo:13:2-13:34]*/#
  {
    integer_array tmp23;
    int tmp24;
    integer_array tmp25;
    modelica_real _$reductionFoldTmpB;
    modelica_real _$reductionFoldTmpA;
    integer_array_create(&tmp25, ((modelica_integer*)&($Pm$Pt1)), 1, :);
    tmp23 = tmp25;
    tmp24 = 1;
    _$reductionFoldTmpB = 0.0; /* defaultValue */
    while (tmp24 <= size_of_dimension_integer_array(tmp23, 1)) {
      modelica_integer $Pi;
      $Pi = *(integer_array_element_addr1(&tmp23, 1, tmp24++));
      tmp22 = get_memory_state();
      if (1) {
        _$reductionFoldTmpA = (&$Pm$Pt2)[(((modelica_integer)$Pi))];
        _$reductionFoldTmpB = ($P$reductionFoldTmpA + $P$reductionFoldTmpB);
      }
    restore_memory_state(tmp22);
    }
    tmp26 = _$reductionFoldTmpB;
  }
  $Pm$Ps = tmp26;
  /*#endModelicaLine*/
  /*#modelicaLine [test.mo:14:2-14:22]*/#
  integer_array_create(&tmp27, ((modelica_integer*)&($Pm$Pt1)), 1, 7);
  real_array_create(&tmp28, ((modelica_real*)&($Pm$Pt2)), 1, 7);
  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_TICK_FN(Test_F1_index);
  #endif
  tmp29 = _Test_F1((modelica_integer)$Pm$Pn, $Prp$Py, $Pm$Ps, tmp27, tmp28);
  #ifdef _OMC_MEASURE_TIME
  SIM_PROF_ACC_FN(Test_F1_index);
  #endif
  $Pm$Pn = tmp29.Test_F1_rettype_1;
  /*#endModelicaLine*/
}

int functionDAE(DATA *data, int *needToIterate)
{
  state mem_state;
  *needToIterate = 0;
  
  mem_state = get_memory_state();
  eqFunction_4(data, _OMC_SEED_HACK_2);
  eqFunction_5(data, _OMC_SEED_HACK_2);
  eqFunction_6(data, _OMC_SEED_HACK_2);
  restore_memory_state(mem_state);
  
  return 0;
}

int function_onlyZeroCrossings(DATA *data, double *gout,double *t)
{
  state mem_state;
  
  mem_state = get_memory_state();
  ZEROCROSSING(0, Less(time, $Prp$PstartTime));
  ZEROCROSSING(1, Less(time, ($Prp$PstartTime + $Prp$Pduration)));
  restore_memory_state(mem_state);
  
  return 0;
}

int checkForDiscreteChanges(DATA *data)
{
  int needToIterate = 0;

  if ($Pm$Pn != $P$PRE$Pm$Pn) { DEBUG_INFO2(LOG_EVENTS,"Discrete Var m.n : %ld to %ld", $P$PRE$Pm$Pn, $Pm$Pn);  needToIterate=1; }
  
  return needToIterate;
}

/* for continuous time variables */
int checkForAsserts(DATA *data)
{

  
  return 0;
}

 int functionJacA(DATA* data, double* jac){
    return 0;
 }

 int functionJacB(DATA* data, double* jac){
    return 0;
 }

 int functionJacC(DATA* data, double* jac){
    return 0;
 }

 int functionJacD(DATA* data, double* jac){
    return 0;
 }

const char *linear_model_frame =
  "model linear_Test.Test1\n  parameter Integer n = 1; // states \n  parameter Integer k = 0; // top-level inputs \n  parameter Integer l = 0; // top-level outputs \n"
  "  parameter Real x0[1] = {%s};\n"
  "  parameter Real u0[0] = {%s};\n"
  "  parameter Real A[1,1] = [%s];\n"
  "  parameter Real B[1,0] = zeros(1,0);%s\n"
  "  parameter Real C[0,1] = zeros(0,1);%s\n"
  "  parameter Real D[0,0] = zeros(0,0);%s\n"
  "  Real x[1](start=x0);\n"
  "  input Real u[0];\n"
  "  output Real y[0];\n"
  "\n  Real x_P$dummy = x[1];\n      \n"
  "equation\n  der(x) = A * x + B * u;\n  y = C * x + D * u;\nend linear_Test.Test1;\n"
;

#ifdef __cplusplus
}
#endif

/* forward the main in the simulation runtime */
extern int _main_SimulationRuntime(int argc, char**argv, DATA *data);

/* call the simulation runtime main from our main! */
int main(int argc, char**argv)
{
  DATA data;
  initializeDataStruc_X_(&data);
  return _main_SimulationRuntime(argc, argv, &data);
}

