/* Events: Sample, Zero Crossings, Relations, Discrete Changes */
/* Simulation code for Modele_stockage_Pia.Tests_2.Tests_composants.Test_KO generated by the OpenModelica Compiler 1.9.1 Beta2 (r19512) (RML version). */

#include "openmodelica.h"
#include "openmodelica_func.h"
#include "simulation_data.h"
#include "simulation/simulation_info_xml.h"
#include "simulation/simulation_runtime.h"
#include "util/omc_error.h"
#include "simulation/solver/model_help.h"
#include "simulation/solver/delay.h"
#include "simulation/solver/linearSystem.h"
#include "simulation/solver/nonlinearSystem.h"
#include "simulation/solver/mixedSystem.h"

#include <assert.h>
#include <string.h>

#include "Modele_stockage_Pia.Tests_2.Tests_composants.Test_KO_functions.h"
#include "Modele_stockage_Pia.Tests_2.Tests_composants.Test_KO_model.h"
#include "Modele_stockage_Pia.Tests_2.Tests_composants.Test_KO_literals.h"



#if defined(HPCOM) && !defined(_OPENMP)
  #error "HPCOM requires OpenMP or the results are wrong"
#endif
#if defined(_OPENMP)
  #include <omp.h>
#else
  /* dummy omp defines */
  #define omp_get_max_threads() 1
#endif

#define threadData data->threadData


/* Initializes the raw time events of the simulation using the now
   calcualted parameters. */
void Modele_stockage_Pia_Tests_2_Tests_composants_Test_KO_function_initSample(DATA *data)
{
  long i=0;

}

const char *Modele_stockage_Pia_Tests_2_Tests_composants_Test_KO_zeroCrossingDescription(int i, int **out_EquationIndexes)
{
  static const char *res[] = {"time > scource_scenario_air1.periode * (1.0 + scource_scenario_air1.count)",
  "time >= scource_scenario_air1.periode * scource_scenario_air1.count and time < scource_scenario_air1.T1 + scource_scenario_air1.periode * scource_scenario_air1.count",
  "time >= scource_scenario_air1.periode * scource_scenario_air1.count + scource_scenario_air1.T1 and time < scource_scenario_air1.T1 + scource_scenario_air1.T0 + scource_scenario_air1.periode * scource_scenario_air1.count",
  "time >= scource_scenario_air1.periode * scource_scenario_air1.count + scource_scenario_air1.T1 + scource_scenario_air1.T0 and time < scource_scenario_air1.T2 + scource_scenario_air1.T1 + scource_scenario_air1.T0 + scource_scenario_air1.periode * scource_scenario_air1.count",
  "time > scource_scenario_air.periode * (1.0 + scource_scenario_air.count)",
  "time >= scource_scenario_air.periode * scource_scenario_air.count and time < scource_scenario_air.T1 + scource_scenario_air.periode * scource_scenario_air.count",
  "time >= scource_scenario_air.periode * scource_scenario_air.count + scource_scenario_air.T1 and time < scource_scenario_air.T1 + scource_scenario_air.T0 + scource_scenario_air.periode * scource_scenario_air.count",
  "time >= scource_scenario_air.periode * scource_scenario_air.count + scource_scenario_air.T1 + scource_scenario_air.T0 and time < scource_scenario_air.T2 + scource_scenario_air.T1 + scource_scenario_air.T0 + scource_scenario_air.periode * scource_scenario_air.count"};
  static const int occurEqs0[] = {1,39};
  static const int occurEqs1[] = {1,41};
  static const int occurEqs2[] = {1,41};
  static const int occurEqs3[] = {1,41};
  static const int occurEqs4[] = {1,39};
  static const int occurEqs5[] = {1,41};
  static const int occurEqs6[] = {1,41};
  static const int occurEqs7[] = {1,41};
  static const int *occurEqs[] = {occurEqs0,occurEqs1,occurEqs2,occurEqs3,occurEqs4,occurEqs5,occurEqs6,occurEqs7};
  *out_EquationIndexes = occurEqs[i];
  return res[i];
}

int Modele_stockage_Pia_Tests_2_Tests_composants_Test_KO_function_ZeroCrossings(DATA *data, double *gout, double *t)
{
  modelica_boolean tmp1034;
  modelica_boolean tmp1035;
  modelica_boolean tmp1036;
  modelica_boolean tmp1037;
  modelica_boolean tmp1038;
  modelica_boolean tmp1039;
  modelica_boolean tmp1040;
  modelica_boolean tmp1041;
  modelica_boolean tmp1042;
  modelica_boolean tmp1043;
  modelica_boolean tmp1044;
  modelica_boolean tmp1045;
  modelica_boolean tmp1046;
  modelica_boolean tmp1047;

  tmp1034 = GreaterZC(time,($Pscource_scenario_air1$Pperiode * (1.0 + $Pscource_scenario_air1$Pcount)), data->simulationInfo.hysteresisEnabled[0]);
  ZEROCROSSING(0, (tmp1034)?1:-1);
  tmp1035 = GreaterEqZC(time,($Pscource_scenario_air1$Pperiode * $Pscource_scenario_air1$Pcount), data->simulationInfo.hysteresisEnabled[1]);
  tmp1036 = LessZC(time,($Pscource_scenario_air1$PT1 + ($Pscource_scenario_air1$Pperiode * $Pscource_scenario_air1$Pcount)), data->simulationInfo.hysteresisEnabled[2]);
  ZEROCROSSING(1, ((tmp1035 && tmp1036))?1:-1);
  tmp1037 = GreaterEqZC(time,(($Pscource_scenario_air1$Pperiode * $Pscource_scenario_air1$Pcount) + $Pscource_scenario_air1$PT1), data->simulationInfo.hysteresisEnabled[3]);
  tmp1038 = LessZC(time,($Pscource_scenario_air1$PT1 + ($Pscource_scenario_air1$PT0 + ($Pscource_scenario_air1$Pperiode * $Pscource_scenario_air1$Pcount))), data->simulationInfo.hysteresisEnabled[4]);
  ZEROCROSSING(2, ((tmp1037 && tmp1038))?1:-1);
  tmp1039 = GreaterEqZC(time,(($Pscource_scenario_air1$Pperiode * $Pscource_scenario_air1$Pcount) + ($Pscource_scenario_air1$PT1 + $Pscource_scenario_air1$PT0)), data->simulationInfo.hysteresisEnabled[5]);
  tmp1040 = LessZC(time,($Pscource_scenario_air1$PT2 + ($Pscource_scenario_air1$PT1 + ($Pscource_scenario_air1$PT0 + ($Pscource_scenario_air1$Pperiode * $Pscource_scenario_air1$Pcount)))), data->simulationInfo.hysteresisEnabled[6]);
  ZEROCROSSING(3, ((tmp1039 && tmp1040))?1:-1);
  tmp1041 = GreaterZC(time,($Pscource_scenario_air$Pperiode * (1.0 + $Pscource_scenario_air$Pcount)), data->simulationInfo.hysteresisEnabled[7]);
  ZEROCROSSING(4, (tmp1041)?1:-1);
  tmp1042 = GreaterEqZC(time,($Pscource_scenario_air$Pperiode * $Pscource_scenario_air$Pcount), data->simulationInfo.hysteresisEnabled[8]);
  tmp1043 = LessZC(time,($Pscource_scenario_air$PT1 + ($Pscource_scenario_air$Pperiode * $Pscource_scenario_air$Pcount)), data->simulationInfo.hysteresisEnabled[9]);
  ZEROCROSSING(5, ((tmp1042 && tmp1043))?1:-1);
  tmp1044 = GreaterEqZC(time,(($Pscource_scenario_air$Pperiode * $Pscource_scenario_air$Pcount) + $Pscource_scenario_air$PT1), data->simulationInfo.hysteresisEnabled[10]);
  tmp1045 = LessZC(time,($Pscource_scenario_air$PT1 + ($Pscource_scenario_air$PT0 + ($Pscource_scenario_air$Pperiode * $Pscource_scenario_air$Pcount))), data->simulationInfo.hysteresisEnabled[11]);
  ZEROCROSSING(6, ((tmp1044 && tmp1045))?1:-1);
  tmp1046 = GreaterEqZC(time,(($Pscource_scenario_air$Pperiode * $Pscource_scenario_air$Pcount) + ($Pscource_scenario_air$PT1 + $Pscource_scenario_air$PT0)), data->simulationInfo.hysteresisEnabled[12]);
  tmp1047 = LessZC(time,($Pscource_scenario_air$PT2 + ($Pscource_scenario_air$PT1 + ($Pscource_scenario_air$PT0 + ($Pscource_scenario_air$Pperiode * $Pscource_scenario_air$Pcount)))), data->simulationInfo.hysteresisEnabled[13]);
  ZEROCROSSING(7, ((tmp1046 && tmp1047))?1:-1);
  
  return 0;
}

const char *Modele_stockage_Pia_Tests_2_Tests_composants_Test_KO_relationDescription(int i)
{
  const char *res[] = {"time > scource_scenario_air1.periode * (1.0 + scource_scenario_air1.count)",
  "time >= scource_scenario_air1.periode * scource_scenario_air1.count",
  "time < scource_scenario_air1.T1 + scource_scenario_air1.periode * scource_scenario_air1.count",
  "time >= scource_scenario_air1.periode * scource_scenario_air1.count + scource_scenario_air1.T1",
  "time < scource_scenario_air1.T1 + scource_scenario_air1.T0 + scource_scenario_air1.periode * scource_scenario_air1.count",
  "time >= scource_scenario_air1.periode * scource_scenario_air1.count + scource_scenario_air1.T1 + scource_scenario_air1.T0",
  "time < scource_scenario_air1.T2 + scource_scenario_air1.T1 + scource_scenario_air1.T0 + scource_scenario_air1.periode * scource_scenario_air1.count",
  "time > scource_scenario_air.periode * (1.0 + scource_scenario_air.count)",
  "time >= scource_scenario_air.periode * scource_scenario_air.count",
  "time < scource_scenario_air.T1 + scource_scenario_air.periode * scource_scenario_air.count",
  "time >= scource_scenario_air.periode * scource_scenario_air.count + scource_scenario_air.T1",
  "time < scource_scenario_air.T1 + scource_scenario_air.T0 + scource_scenario_air.periode * scource_scenario_air.count",
  "time >= scource_scenario_air.periode * scource_scenario_air.count + scource_scenario_air.T1 + scource_scenario_air.T0",
  "time < scource_scenario_air.T2 + scource_scenario_air.T1 + scource_scenario_air.T0 + scource_scenario_air.periode * scource_scenario_air.count"};
  return res[i];
};

int Modele_stockage_Pia_Tests_2_Tests_composants_Test_KO_function_updateRelations(DATA *data, int evalforZeroCross)
{
  modelica_boolean tmp1048;
  modelica_boolean tmp1049;
  modelica_boolean tmp1050;
  modelica_boolean tmp1051;
  modelica_boolean tmp1052;
  modelica_boolean tmp1053;
  modelica_boolean tmp1054;
  modelica_boolean tmp1055;
  modelica_boolean tmp1056;
  modelica_boolean tmp1057;
  modelica_boolean tmp1058;
  modelica_boolean tmp1059;
  modelica_boolean tmp1060;
  modelica_boolean tmp1061;
  
  if(evalforZeroCross)
  {
    tmp1048 = GreaterZC(time,($Pscource_scenario_air1$Pperiode * (1.0 + $Pscource_scenario_air1$Pcount)), data->simulationInfo.hysteresisEnabled[0]);
    data->simulationInfo.relations[0] = tmp1048;
    tmp1049 = GreaterEqZC(time,($Pscource_scenario_air1$Pperiode * $Pscource_scenario_air1$Pcount), data->simulationInfo.hysteresisEnabled[1]);
    data->simulationInfo.relations[1] = tmp1049;
    tmp1050 = LessZC(time,($Pscource_scenario_air1$PT1 + ($Pscource_scenario_air1$Pperiode * $Pscource_scenario_air1$Pcount)), data->simulationInfo.hysteresisEnabled[2]);
    data->simulationInfo.relations[2] = tmp1050;
    tmp1051 = GreaterEqZC(time,(($Pscource_scenario_air1$Pperiode * $Pscource_scenario_air1$Pcount) + $Pscource_scenario_air1$PT1), data->simulationInfo.hysteresisEnabled[3]);
    data->simulationInfo.relations[3] = tmp1051;
    tmp1052 = LessZC(time,($Pscource_scenario_air1$PT1 + ($Pscource_scenario_air1$PT0 + ($Pscource_scenario_air1$Pperiode * $Pscource_scenario_air1$Pcount))), data->simulationInfo.hysteresisEnabled[4]);
    data->simulationInfo.relations[4] = tmp1052;
    tmp1053 = GreaterEqZC(time,(($Pscource_scenario_air1$Pperiode * $Pscource_scenario_air1$Pcount) + ($Pscource_scenario_air1$PT1 + $Pscource_scenario_air1$PT0)), data->simulationInfo.hysteresisEnabled[5]);
    data->simulationInfo.relations[5] = tmp1053;
    tmp1054 = LessZC(time,($Pscource_scenario_air1$PT2 + ($Pscource_scenario_air1$PT1 + ($Pscource_scenario_air1$PT0 + ($Pscource_scenario_air1$Pperiode * $Pscource_scenario_air1$Pcount)))), data->simulationInfo.hysteresisEnabled[6]);
    data->simulationInfo.relations[6] = tmp1054;
    tmp1055 = GreaterZC(time,($Pscource_scenario_air$Pperiode * (1.0 + $Pscource_scenario_air$Pcount)), data->simulationInfo.hysteresisEnabled[7]);
    data->simulationInfo.relations[7] = tmp1055;
    tmp1056 = GreaterEqZC(time,($Pscource_scenario_air$Pperiode * $Pscource_scenario_air$Pcount), data->simulationInfo.hysteresisEnabled[8]);
    data->simulationInfo.relations[8] = tmp1056;
    tmp1057 = LessZC(time,($Pscource_scenario_air$PT1 + ($Pscource_scenario_air$Pperiode * $Pscource_scenario_air$Pcount)), data->simulationInfo.hysteresisEnabled[9]);
    data->simulationInfo.relations[9] = tmp1057;
    tmp1058 = GreaterEqZC(time,(($Pscource_scenario_air$Pperiode * $Pscource_scenario_air$Pcount) + $Pscource_scenario_air$PT1), data->simulationInfo.hysteresisEnabled[10]);
    data->simulationInfo.relations[10] = tmp1058;
    tmp1059 = LessZC(time,($Pscource_scenario_air$PT1 + ($Pscource_scenario_air$PT0 + ($Pscource_scenario_air$Pperiode * $Pscource_scenario_air$Pcount))), data->simulationInfo.hysteresisEnabled[11]);
    data->simulationInfo.relations[11] = tmp1059;
    tmp1060 = GreaterEqZC(time,(($Pscource_scenario_air$Pperiode * $Pscource_scenario_air$Pcount) + ($Pscource_scenario_air$PT1 + $Pscource_scenario_air$PT0)), data->simulationInfo.hysteresisEnabled[12]);
    data->simulationInfo.relations[12] = tmp1060;
    tmp1061 = LessZC(time,($Pscource_scenario_air$PT2 + ($Pscource_scenario_air$PT1 + ($Pscource_scenario_air$PT0 + ($Pscource_scenario_air$Pperiode * $Pscource_scenario_air$Pcount)))), data->simulationInfo.hysteresisEnabled[13]);
    data->simulationInfo.relations[13] = tmp1061;
  }
  else
  {
    data->simulationInfo.relations[0] = (time > ($Pscource_scenario_air1$Pperiode * (1.0 + $Pscource_scenario_air1$Pcount)));
    data->simulationInfo.relations[1] = (time >= ($Pscource_scenario_air1$Pperiode * $Pscource_scenario_air1$Pcount));
    data->simulationInfo.relations[2] = (time < ($Pscource_scenario_air1$PT1 + ($Pscource_scenario_air1$Pperiode * $Pscource_scenario_air1$Pcount)));
    data->simulationInfo.relations[3] = (time >= (($Pscource_scenario_air1$Pperiode * $Pscource_scenario_air1$Pcount) + $Pscource_scenario_air1$PT1));
    data->simulationInfo.relations[4] = (time < ($Pscource_scenario_air1$PT1 + ($Pscource_scenario_air1$PT0 + ($Pscource_scenario_air1$Pperiode * $Pscource_scenario_air1$Pcount))));
    data->simulationInfo.relations[5] = (time >= (($Pscource_scenario_air1$Pperiode * $Pscource_scenario_air1$Pcount) + ($Pscource_scenario_air1$PT1 + $Pscource_scenario_air1$PT0)));
    data->simulationInfo.relations[6] = (time < ($Pscource_scenario_air1$PT2 + ($Pscource_scenario_air1$PT1 + ($Pscource_scenario_air1$PT0 + ($Pscource_scenario_air1$Pperiode * $Pscource_scenario_air1$Pcount)))));
    data->simulationInfo.relations[7] = (time > ($Pscource_scenario_air$Pperiode * (1.0 + $Pscource_scenario_air$Pcount)));
    data->simulationInfo.relations[8] = (time >= ($Pscource_scenario_air$Pperiode * $Pscource_scenario_air$Pcount));
    data->simulationInfo.relations[9] = (time < ($Pscource_scenario_air$PT1 + ($Pscource_scenario_air$Pperiode * $Pscource_scenario_air$Pcount)));
    data->simulationInfo.relations[10] = (time >= (($Pscource_scenario_air$Pperiode * $Pscource_scenario_air$Pcount) + $Pscource_scenario_air$PT1));
    data->simulationInfo.relations[11] = (time < ($Pscource_scenario_air$PT1 + ($Pscource_scenario_air$PT0 + ($Pscource_scenario_air$Pperiode * $Pscource_scenario_air$Pcount))));
    data->simulationInfo.relations[12] = (time >= (($Pscource_scenario_air$Pperiode * $Pscource_scenario_air$Pcount) + ($Pscource_scenario_air$PT1 + $Pscource_scenario_air$PT0)));
    data->simulationInfo.relations[13] = (time < ($Pscource_scenario_air$PT2 + ($Pscource_scenario_air$PT1 + ($Pscource_scenario_air$PT0 + ($Pscource_scenario_air$Pperiode * $Pscource_scenario_air$Pcount)))));
  }
  
  return 0;
}

int Modele_stockage_Pia_Tests_2_Tests_composants_Test_KO_checkForDiscreteChanges(DATA *data)
{
  int needToIterate = 0;

  infoStreamPrint(LOG_EVENTS_V, 1, "check for discrete changes");
  if($P$whenCondition2 != $P$PRE$P$whenCondition2)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition2 from %d to %d", $P$PRE$P$whenCondition2, $P$whenCondition2);
    needToIterate = 1;
  }
  if($Pscource_scenario_air$Pcount != $P$PRE$Pscource_scenario_air$Pcount)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: scource_scenario_air._count from %g to %g", $P$PRE$Pscource_scenario_air$Pcount, $Pscource_scenario_air$Pcount);
    needToIterate = 1;
  }
  if($Pscource_scenario_air$Py != $P$PRE$Pscource_scenario_air$Py)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: scource_scenario_air._y from %ld to %ld", $P$PRE$Pscource_scenario_air$Py, $Pscource_scenario_air$Py);
    needToIterate = 1;
  }
  if($P$whenCondition1 != $P$PRE$P$whenCondition1)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: $whenCondition1 from %d to %d", $P$PRE$P$whenCondition1, $P$whenCondition1);
    needToIterate = 1;
  }
  if($Pscource_scenario_air1$Pcount != $P$PRE$Pscource_scenario_air1$Pcount)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: scource_scenario_air1._count from %g to %g", $P$PRE$Pscource_scenario_air1$Pcount, $Pscource_scenario_air1$Pcount);
    needToIterate = 1;
  }
  if($Pscource_scenario_air1$Py != $P$PRE$Pscource_scenario_air1$Py)
  {
    infoStreamPrint(LOG_EVENTS_V, 0, "discrete var changed: scource_scenario_air1._y from %ld to %ld", $P$PRE$Pscource_scenario_air1$Py, $Pscource_scenario_air1$Py);
    needToIterate = 1;
  }
  if (ACTIVE_STREAM(LOG_EVENTS_V)) messageClose(LOG_EVENTS_V);
  
  return needToIterate;
}


