model Reconciled_NewDataReconciliationSimpleTests_TSP_FourFlows5
  /* This is not Complete ThermoSysPro variables and functions needs to be corrected manually */
  //Variables of Interest
  parameter Real singularPressureLoss1_Q = 2.10;
  parameter Real singularPressureLoss1_T = 470;
  parameter Real singularPressureLoss1_Pm = 1550000;
  parameter Real singularPressureLoss2_Q = 1.91;
  parameter Real singularPressureLoss2_T = 465;
  parameter Real singularPressureLoss2_Pm = 1500000;
  parameter Real singularPressureLoss3_Q = 0.95;
  parameter Real singularPressureLoss3_T = 473;
  parameter Real singularPressureLoss3_Pm = 1490000;
  parameter Real singularPressureLoss4_Q = 2.00;
  parameter Real singularPressureLoss4_T = 462;
  parameter Real singularPressureLoss4_Pm = 1400000;
  parameter Real staticDrum1_T = 470;
  parameter Real staticDrum1_P = 1450000;
  parameter Real mixer21_P = 1450000;
  parameter Real mixer21_T = 475;
  //parameters in SET-S
  parameter Real singularPressureLoss1_K = 0.0001;
  parameter Integer singularPressureLoss1_mode = 0;
  parameter Real singularPressureLoss2_K = 0.0001;
  parameter Integer singularPressureLoss2_mode = 0;
  parameter Real singularPressureLoss3_K = 0.0001;
  parameter Integer singularPressureLoss3_mode = 0;
  parameter Real singularPressureLoss4_K = 0.0001;
  parameter Integer singularPressureLoss4_mode = 0;
  parameter Real staticDrum1_x = 1.0;
  parameter Integer mixer21_mode = 0;
  //residualVars
  Real res_F_1;
  Real res_F_2;
  Real res_F_3;
  Real res_F_4;
  Real res_F_5;
  Real res_F_6;
  Real res_F_7;
  Real res_F_8;
  Real res_F_9;
  Real res_F_10;
  Real res_F_11;
  Real res_F_12;
  Real res_F_13;
  Real res_F_14;
  //remaining variables in setS
  Real staticDrum1_Cs_eva_P;
  Real staticDrum1_Cs_sur_P;
  Real staticDrum1_Ce_sup_P;
  Real staticDrum1_Ce_steam_h_vol;
  Real staticDrum1_lsat_P = staticDrum1_lsat.P;
  Real staticDrum1_lsat_T = staticDrum1_lsat.T;
  Real staticDrum1_lsat_rho = staticDrum1_lsat.rho;
  Real staticDrum1_vsat_P = staticDrum1_vsat.P;
  Real staticDrum1_vsat_T = staticDrum1_vsat.T;
  Real staticDrum1_vsat_rho = staticDrum1_vsat.rho;
  Real staticDrum1_vsat_h = staticDrum1_vsat.h;
  Real singularPressureLoss1_C2_h_vol;
  Real staticDrum1_Ce_sup_h_vol;
  Real staticDrum1_Ce_eva_h_vol;
  Real staticDrum1_Ce_eco_h_vol;
  Real staticDrum1_Cs_purg_h_vol;
  Real staticDrum1_Cs_sup_h_vol;
  Real staticDrum1_Cs_eva_h_vol;
  Real staticDrum1_lsat_h = staticDrum1_lsat.h;
  Real staticDrum1_hl;
  Real staticDrum1_hv;
  Real staticDrum1_Cs_sur_h_vol;
  Real sink1_Q;
  Real sink1_C_Q;
  Real singularPressureLoss4_C2_Q;
  Real singularPressureLoss4_C1_Q;
  Real mixer21_pro_pT_d = mixer21_pro_pT.d;
  Real singularPressureLoss3_C2_h_vol;
  Real singularPressureLoss2_C2_h_vol;
  Real mixer21_Ce1_h_vol;
  Real mixer21_Ce2_h_vol;
  Real mixer21_pro_pT_h = mixer21_pro_pT.h;
  Real mixer21_h;
  Real mixer21_Cs_h_vol;
  Real mixer21_Ce2_P;
  Real mixer21_Cs_P;
  Real sink1_P;
  Real sink1_C_P;
  Real sink1_C_h;
  Real singularPressureLoss4_C2_h;
  Real singularPressureLoss4_C1_h_vol;
  Real singularPressureLoss4_C1_h;
  Real singularPressureLoss4_h;
  Real singularPressureLoss4_pro_pT_h = singularPressureLoss4_pro_pT.h;
  Real singularPressureLoss4_pro_pT_d = singularPressureLoss4_pro_pT.d;
  Real singularPressureLoss4_rho;
  Real singularPressureLoss4_deltaP;
  Real singularPressureLoss4_C1_P;
  Real singularPressureLoss4_C2_P;
  Real mixer21_Ce1_P;
  Real sourceQ1_P;
  Real sourceQ1_C_P;
  Real singularPressureLoss1_C1_P;
  Real singularPressureLoss1_C2_P;
  Real singularPressureLoss1_deltaP;
  Real singularPressureLoss1_rho;
  Real singularPressureLoss1_pro_pT_d = singularPressureLoss1_pro_pT.d;
  Real singularPressureLoss1_pro_pT_h = singularPressureLoss1_pro_pT.h;
  Real singularPressureLoss1_h;
  Real singularPressureLoss1_C1_h_vol;
  Real sourceQ1_C_h;
  Real singularPressureLoss1_C1_h;
  Real singularPressureLoss1_C2_h;
  Real singularPressureLoss2_C2_h;
  Real singularPressureLoss2_C1_P;
  Real singularPressureLoss2_C2_P;
  Real singularPressureLoss2_deltaP;
  Real singularPressureLoss2_rho;
  Real singularPressureLoss2_pro_pT_d = singularPressureLoss2_pro_pT.d;
  Real singularPressureLoss2_pro_pT_h = singularPressureLoss2_pro_pT.h;
  Real singularPressureLoss2_h;
  Real singularPressureLoss2_C1_h_vol;
  Real singularPressureLoss2_C1_h;
  Real singularPressureLoss1_C1_Q;
  Real singularPressureLoss1_C2_Q;
  Real staticDrum1_Ce_eva_Q;
  Real staticDrum1_Ce_eva_h;
  Real staticDrum1_Ce_eco_Q;
  Real staticDrum1_Ce_eco_h;
  Real staticDrum1_Cs_sup_Q;
  Real staticDrum1_Cs_sup_h;
  Real staticDrum1_Cs_eva_Q;
  Real staticDrum1_Cs_eva_h;
  Real staticDrum1_Cs_sur_h;
  Real staticDrum1_Cs_purg_Q;
  Real staticDrum1_Cs_purg_h;
  Real staticDrum1_Ce_steam_Q;
  Real staticDrum1_Ce_steam_h;
  Real staticDrum1_Ce_sup_Q;
  Real staticDrum1_Ce_sup_h;
  Real staticDrum1_Cth_W;
  Real staticDrum1_Cs_sur_Q;
  Real singularPressureLoss2_C1_Q;
  Real singularPressureLoss2_C2_Q;
  Real mixer21_Oalpha1_signal;
  Real mixer21_alpha1;
  Real singularPressureLoss3_C1_Q;
  Real singularPressureLoss3_C2_Q;
  Real mixer21_Ce2_Q;
  Real mixer21_Cs_Q;
  Real mixer21_Cs_h;
  Real mixer21_Ce1_Q;
  Real mixer21_Ce1_h;
  Real mixer21_Ce2_h;
  Real singularPressureLoss3_C2_h;
  Real singularPressureLoss3_C1_P;
  Real singularPressureLoss3_C2_P;
  Real singularPressureLoss3_deltaP;
  Real singularPressureLoss3_rho;
  Real singularPressureLoss3_pro_pT_d = singularPressureLoss3_pro_pT.d;
  Real singularPressureLoss3_pro_pT_h = singularPressureLoss3_pro_pT.h;
  Real singularPressureLoss3_h;
  Real singularPressureLoss3_C1_h_vol;
  Real singularPressureLoss3_C1_h;
  ThermoSysPro.Properties.WaterSteam.Common.ThermoProperties_pT singularPressureLoss1_pro_pT, singularPressureLoss2_pro_pT, singularPressureLoss3_pro_pT, singularPressureLoss4_pro_pT, mixer21_pro_pT;
  ThermoSysPro.Properties.WaterSteam.Common.PropThermoSat staticDrum1_lsat, staticDrum1_vsat;
equation
//set-C Canonical form
  res_F_1 = staticDrum1_Cs_eva_h - singularPressureLoss3_C1_h;
  res_F_2 = staticDrum1_Cs_eva_Q - singularPressureLoss3_C1_Q;
  res_F_3 = singularPressureLoss2_C2_P - mixer21_Ce1_P;
  res_F_4 = singularPressureLoss4_C1_P - mixer21_Cs_P;
  res_F_5 = singularPressureLoss3_C2_P - mixer21_Ce2_P;
  res_F_6 = singularPressureLoss4_C1_h_vol - mixer21_Cs_h_vol;
  res_F_7 = singularPressureLoss4_C1_Q - mixer21_Cs_Q;
  res_F_8 = singularPressureLoss4_C1_h - mixer21_Cs_h;
  res_F_9 = staticDrum1_Cs_sur_h_vol - singularPressureLoss2_C1_h_vol;
  res_F_10 = staticDrum1_Cs_eva_h_vol - singularPressureLoss3_C1_h_vol;
  res_F_11 = staticDrum1_lsat_T - staticDrum1_T;
  res_F_12 = staticDrum1_Ce_sup_P - singularPressureLoss1_C2_P;
  res_F_13 = staticDrum1_Cs_sur_P - singularPressureLoss2_C1_P;
  res_F_14 = staticDrum1_Cs_eva_P - singularPressureLoss3_C1_P;
//remaining equations in Set-S
  staticDrum1_P = staticDrum1_Cs_eva_P;
  staticDrum1_P = staticDrum1_Cs_sur_P;
  staticDrum1_P = staticDrum1_Ce_sup_P;
  staticDrum1_Ce_steam_h_vol = staticDrum1_hv;
  staticDrum1_hv = staticDrum1_vsat_h;
  (staticDrum1_lsat, staticDrum1_vsat) = ThermoSysPro.Properties.WaterSteam.IF97.Water_sat_P(staticDrum1_P);
  singularPressureLoss1_C2_h_vol = staticDrum1_Ce_sup_h_vol;
  staticDrum1_Ce_sup_h_vol = staticDrum1_hl;
  staticDrum1_Ce_eva_h_vol = staticDrum1_hl;
  staticDrum1_Ce_eco_h_vol = staticDrum1_hl;
  staticDrum1_Cs_purg_h_vol = staticDrum1_hl;
  staticDrum1_Cs_sup_h_vol = staticDrum1_hl;
  staticDrum1_Cs_eva_h_vol = staticDrum1_hl;
  staticDrum1_hl = staticDrum1_lsat_h;
  staticDrum1_Cs_sur_h_vol = (1.0 - staticDrum1_x) * staticDrum1_hl + staticDrum1_x * staticDrum1_hv;
  sink1_C_Q = sink1_Q;
  singularPressureLoss4_C2_Q = sink1_C_Q;
  singularPressureLoss4_C2_Q = singularPressureLoss4_C1_Q;
  singularPressureLoss4_Q = singularPressureLoss4_C1_Q;
  mixer21_pro_pT = ThermoSysPro.Properties.WaterSteam.IF97.Water_PT(mixer21_P, mixer21_T, mixer21_mode);
  mixer21_Ce2_h_vol = singularPressureLoss3_C2_h_vol;
  mixer21_Ce1_h_vol = singularPressureLoss2_C2_h_vol;
  mixer21_Ce1_h_vol = mixer21_h;
  mixer21_Ce2_h_vol = mixer21_h;
  mixer21_h = mixer21_pro_pT_h;
  mixer21_Cs_h_vol = mixer21_h;
  mixer21_P = mixer21_Ce2_P;
  mixer21_P = mixer21_Cs_P;
  sink1_C_P = sink1_P;
  singularPressureLoss4_C2_P = sink1_C_P;
  singularPressureLoss4_C2_h = sink1_C_h;
  singularPressureLoss4_C2_h = singularPressureLoss4_C1_h;
  0.0 = singularPressureLoss4_C1_h - singularPressureLoss4_C1_h_vol;
  singularPressureLoss4_h = singularPressureLoss4_C1_h;
  singularPressureLoss4_h = singularPressureLoss4_pro_pT_h;
  singularPressureLoss4_pro_pT = ThermoSysPro.Properties.WaterSteam.IF97.Water_PT(singularPressureLoss4_Pm, singularPressureLoss4_T, singularPressureLoss4_mode);
  singularPressureLoss4_rho = singularPressureLoss4_pro_pT_d;
  singularPressureLoss4_deltaP = singularPressureLoss4_K * (singularPressureLoss4_Q * abs(singularPressureLoss4_Q) / singularPressureLoss4_rho);
  singularPressureLoss4_C1_P - singularPressureLoss4_C2_P = singularPressureLoss4_deltaP;
  singularPressureLoss4_Pm = 0.5 * (singularPressureLoss4_C1_P + singularPressureLoss4_C2_P);
  mixer21_P = mixer21_Ce1_P;
  staticDrum1_Cth_W = 0.0;
  singularPressureLoss1_pro_pT = ThermoSysPro.Properties.WaterSteam.IF97.Water_PT(singularPressureLoss1_Pm, singularPressureLoss1_T, singularPressureLoss1_mode);
  sourceQ1_C_P = sourceQ1_P;
  singularPressureLoss1_Pm = 0.5 * (singularPressureLoss1_C1_P + singularPressureLoss1_C2_P);
  singularPressureLoss1_C1_P = sourceQ1_C_P;
  singularPressureLoss1_C1_P - singularPressureLoss1_C2_P = singularPressureLoss1_deltaP;
  singularPressureLoss1_deltaP = singularPressureLoss1_K * (singularPressureLoss1_Q * abs(singularPressureLoss1_Q) / singularPressureLoss1_rho);
  singularPressureLoss1_rho = singularPressureLoss1_pro_pT_d;
  singularPressureLoss1_h = singularPressureLoss1_pro_pT_h;
  singularPressureLoss1_h = singularPressureLoss1_C1_h;
  0.0 = singularPressureLoss1_C1_h - singularPressureLoss1_C1_h_vol;
  singularPressureLoss1_C1_h = sourceQ1_C_h;
  singularPressureLoss1_C2_h = singularPressureLoss1_C1_h;
  singularPressureLoss1_C2_h = staticDrum1_Ce_sup_h;
  staticDrum1_Ce_steam_h = 100000.0;
  staticDrum1_Cs_purg_h = 100000.0;
  mixer21_Ce1_h = singularPressureLoss2_C2_h;
  singularPressureLoss2_C2_h = singularPressureLoss2_C1_h;
  singularPressureLoss2_pro_pT = ThermoSysPro.Properties.WaterSteam.IF97.Water_PT(singularPressureLoss2_Pm, singularPressureLoss2_T, singularPressureLoss2_mode);
  singularPressureLoss2_Pm = 0.5 * (singularPressureLoss2_C1_P + singularPressureLoss2_C2_P);
  singularPressureLoss2_C1_P - singularPressureLoss2_C2_P = singularPressureLoss2_deltaP;
  singularPressureLoss2_deltaP = singularPressureLoss2_K * (singularPressureLoss2_Q * abs(singularPressureLoss2_Q) / singularPressureLoss2_rho);
  singularPressureLoss2_rho = singularPressureLoss2_pro_pT_d;
  singularPressureLoss2_h = singularPressureLoss2_pro_pT_h;
  singularPressureLoss2_h = singularPressureLoss2_C1_h;
  0.0 = singularPressureLoss2_C1_h - singularPressureLoss2_C1_h_vol;
  singularPressureLoss2_C1_h = staticDrum1_Cs_sur_h;
  staticDrum1_Cs_sup_h = 100000.0;
  staticDrum1_Ce_eco_h = 100000.0;
  staticDrum1_Ce_eva_h = 100000.0;
  singularPressureLoss1_Q = singularPressureLoss1_C1_Q;
  singularPressureLoss1_C2_Q = singularPressureLoss1_C1_Q;
  singularPressureLoss1_C2_Q = staticDrum1_Ce_sup_Q;
  staticDrum1_Ce_steam_Q = 0.0;
  staticDrum1_Cs_purg_Q = 0.0;
  staticDrum1_Cs_sup_Q = 0.0;
  staticDrum1_Ce_eco_Q = 0.0;
  staticDrum1_Ce_eva_Q = 0.0;
  staticDrum1_Ce_eco_Q + staticDrum1_Ce_steam_Q + staticDrum1_Ce_sup_Q + staticDrum1_Ce_eva_Q + (-staticDrum1_Cs_sup_Q) - staticDrum1_Cs_eva_Q - staticDrum1_Cs_sur_Q - staticDrum1_Cs_purg_Q = 0.0;
  staticDrum1_Ce_eco_Q * staticDrum1_Ce_eco_h + staticDrum1_Ce_steam_Q * staticDrum1_Ce_steam_h + staticDrum1_Ce_sup_Q * staticDrum1_Ce_sup_h + staticDrum1_Ce_eva_Q * staticDrum1_Ce_eva_h + staticDrum1_Cth_W + (-staticDrum1_Cs_purg_Q) * staticDrum1_Cs_purg_h - staticDrum1_Cs_sur_Q * staticDrum1_Cs_sur_h - staticDrum1_Cs_eva_Q * staticDrum1_Cs_eva_h - staticDrum1_Cs_sup_Q * staticDrum1_Cs_sup_h = 0.0;
  singularPressureLoss2_Q = singularPressureLoss2_C1_Q;
  singularPressureLoss2_C1_Q = staticDrum1_Cs_sur_Q;
  singularPressureLoss2_C2_Q = singularPressureLoss2_C1_Q;
  mixer21_Ce1_Q = singularPressureLoss2_C2_Q;
  mixer21_Oalpha1_signal = mixer21_alpha1;
  mixer21_alpha1 = mixer21_Ce1_Q / mixer21_Cs_Q;
  0.0 = mixer21_Ce1_Q + mixer21_Ce2_Q - mixer21_Cs_Q;
  singularPressureLoss3_Q = singularPressureLoss3_C1_Q;
  singularPressureLoss3_C2_Q = singularPressureLoss3_C1_Q;
  mixer21_Ce2_Q = singularPressureLoss3_C2_Q;
  0.0 = mixer21_Ce1_Q * mixer21_Ce1_h + mixer21_Ce2_Q * mixer21_Ce2_h - mixer21_Cs_Q * mixer21_Cs_h;
  mixer21_Ce2_h = singularPressureLoss3_C2_h;
  singularPressureLoss3_C2_h = singularPressureLoss3_C1_h;
  singularPressureLoss3_pro_pT = ThermoSysPro.Properties.WaterSteam.IF97.Water_PT(singularPressureLoss3_Pm, singularPressureLoss3_T, singularPressureLoss3_mode);
  singularPressureLoss3_Pm = 0.5 * (singularPressureLoss3_C1_P + singularPressureLoss3_C2_P);
  singularPressureLoss3_C1_P - singularPressureLoss3_C2_P = singularPressureLoss3_deltaP;
  singularPressureLoss3_deltaP = singularPressureLoss3_K * (singularPressureLoss3_Q * abs(singularPressureLoss3_Q) / singularPressureLoss3_rho);
  singularPressureLoss3_rho = singularPressureLoss3_pro_pT_d;
  singularPressureLoss3_h = singularPressureLoss3_pro_pT_h;
  singularPressureLoss3_h = singularPressureLoss3_C1_h;
  0.0 = singularPressureLoss3_C1_h - singularPressureLoss3_C1_h_vol;
  annotation(
    experiment(StartTime = 0, StopTime = 1, Tolerance = 1e-6, Interval = 0.002),
    __OpenModelica_simulationFlags(lv = "LOG_STATS", s = "dassl"));
end Reconciled_NewDataReconciliationSimpleTests_TSP_FourFlows5;
